name: Deploy Angular and Rust to Sakura VPS

on:
  push:
    branches: [ master, main ]

# env:
#   SFTP_HOST: <さくらVPSのホスト名>
#   SFTP_USERNAME: <SFTPユーザー名>
#   SFTP_PASSWORD: <SFTPパスワード>
#   ANGULAR_DIR: <Angularプロジェクトのディレクトリパス>
#   RUST_DIR: <Rustプロジェクトのディレクトリパス>

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js v20.x
        run: |
          curl -sL https://deb.nodesource.com/setup_20.x | bash -s
          sudo apt-get install -y nodejs
          node -v
          npm -v

      - name: Install Rust v1.77
        run: |
          curl -sSL https://sh.rust-lang.org/install.sh | bash
          source $HOME/.cargo/env
          rustc -V

      - name: Build Angular application
        run: |
          cd frondend
          npm install
          ng build --configuration production

      - name: Build Rust application
        run: |
          cd backend/my_actix_app
          cargo build --release

      - name: Deploy Angular app
        run: |
          sftp ${{ env.SFTP_USERNAME }}@${{ env.SFTP_HOST }} << EOF
          mkdir -p ${{ env.ANGULAR_DIR }}
          put -r dist/* ${{ env.ANGULAR_DIR }}
          EOF

      - name: Deploy Rust app
        run: |
          sftp ${{ env.SFTP_USERNAME }}@${{ env.SFTP_HOST }} << EOF
          mkdir -p ${{ env.RUST_DIR }}
          put -r target/release/* ${{ env.RUST_DIR }}
          EOF
