[package]
name = "my_actix_app"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.5.1"
actix-cors = "0.7.0"
mysql = "20.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
